import pytest
from tools.filesystem import list_files, read_file, write_file


def test_list_files_excludes_internal_directories(tmp_path):
    # Create a normal source file.
    (tmp_path / "main.py").write_text("print('hello')")

    # Create directories that should be excluded.
    git_dir = tmp_path / ".git"
    git_dir.mkdir()
    (git_dir / "config").write_text("git configuration")

    cache_dir = tmp_path / "__pycache__"
    cache_dir.mkdir()
    (cache_dir / "main.pyc").write_text("cache")

    # Run our filesystem tool.
    files = list_files(tmp_path)

    # Check the result.
    assert str(tmp_path / "main.py") in files
    assert str(git_dir / "config") not in files
    assert str(cache_dir / "main.pyc") not in files


def test_read_file(tmp_path):
    test_file = tmp_path / "example.py"
    test_file.write_text("print('hello')")

    content = read_file("example.py", root=tmp_path)

    assert content == "print('hello')"


def test_read_file_blocks_outside_project(tmp_path):
    outside_file = tmp_path.parent / "secret.txt"
    outside_file.write_text("secret information")

    with pytest.raises(ValueError):
        read_file("../secret.txt", root=tmp_path)


def test_write_file(tmp_path):
    write_file(
        "generated/example.py",
        "print('generated by developer')",
        root=tmp_path,
    )

    created_file = tmp_path / "generated" / "example.py"

    assert created_file.exists()
    assert created_file.read_text() == "print('generated by developer')"


def test_write_file_blocks_outside_project(tmp_path):
    with pytest.raises(ValueError):
        write_file(
            "../outside.txt",
            "should not be written",
            root=tmp_path,
        )